# Your Solution
version: '3'

services:

  postgres:
    image: postgres:13
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sit722_part5_aaaf_user
      POSTGRES_PASSWORD: CMLIfDEWuS9jr6GMEmSNS8X3BTgIoGmg
      POSTGRES_DB: sit722_part5_aaaf
    restart: always

  book_catalog:
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    image: sit722sandara.azurecr.io/book_catalog:latest
    container_name: book-catalog
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://sit722_part5_aaaf_user:CMLIfDEWuS9jr6GMEmSNS8X3BTgIoGmg@dpg-cs33o8t6l47c73e92dh0-a.oregon-postgres.render.com/sit722_part5_aaaf
    depends_on:
      - postgres
    restart: "no"
    platform: linux/amd64

  inventory_management:
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    image: sit722sandara.azurecr.io/inventory_management:latest
    container_name: inventory-management
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://sit722_part5_aaaf_user:CMLIfDEWuS9jr6GMEmSNS8X3BTgIoGmg@dpg-cs33o8t6l47c73e92dh0-a.oregon-postgres.render.com/sit722_part5_aaaf
    depends_on:
      - postgres
    restart: "no"
    platform: linux/amd64
