apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
      - name: inventory-management
        image: $CONTAINER_REGISTRY/inventory_management:$VERSION
        ports:
        - containerPort: 8001
        env:
        - name: DATABASE_URL
          value: "postgresql://sit722_part5_aaaf_user:CMLIfDEWuS9jr6GMEmSNS8X3BTgIoGmg@dpg-cs33o8t6l47c73e92dh0-a.oregon-postgres.render.com/sit722_part5_aaaf"

---


apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  selector:
    app: inventory-management
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: LoadBalancer
