ame: Terraform Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.4.0

    # Authenticate Azure
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Apply Terraform changes (create container registry, Kubernetes cluster, etc.)
    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve

    # Output the resources created
    - name: Terraform Output
      run: terraform output

    # Save Kubernetes config for later use
    - name: Save KubeConfig
      run: echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

